# services:
#   mysql:
#     image: mysql:latest
#     container_name: mysql-container
#     environment:
#       MYSQL_ROOT_PASSWORD: my-secret-pw
#       MYSQL_DATABASE: sabores_peruanos
#     ports:
#       - "3306:3306"
#     networks:
#       - my-network
#     volumes:
#       - mysql-data:/var/lib/mysql

# networks:
#   my-network:
#     driver: bridge

# volumes:
#   mysql-data:
