services:
  php:
    image: php
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: container_php
    volumes:
      - ./paginaWeb:/var/www/html
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - db

  db:
    image: mysql
    container_name: container_mysql
    environment:
      MYSQL_ROOT_PASSWORD: clave
      MYSQL_DATABASE: sabores_peruanos
    ports:
    - "3306:3306"
    volumes:
    - ./db_data:/docker-entrypoint-initdb.d
    - db_data:/var/lib/mysql

volumes:
  db_data:
